# Generated by Django 4.0.4 on 2023-01-11 12:14

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='equipe', variations={'thumb': {'crop': True, 'height': 480, 'width:': 480}}, verbose_name='Imagem'),
        ),
    ]
