# Generated by Django 4.0.4 on 2023-01-11 12:45

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width:': 480}}, verbose_name='Imagem'),
        ),
    ]
